newElement( "ul", [ "id.append", "articles-menu" ], 0, [ "articles-type" ] );
newElement( "a", [ "querySelector.append", "#articles-menu>.articles-type:last-of-type" ], 0, [ "underline-hover" ], 0, [ ["href", "#"] ], "menu features" );
    newElement( "li", [ "querySelector.append", "#articles-menu>.articles-type:last-of-type" ], 0, [ "article" ] );
        newElement( "a", [ "querySelector.append", "#articles-menu>.articles-type:last-of-type>.article:last-of-type" ], 0, [ "underline-hover" ], 0, [ ["href","#"] ], "auto uppercase" );
    newElement( "li", [ "querySelector.append", "#articles-menu>.articles-type:last-of-type" ], 0, [ "article" ] );
        newElement( "a", [ "querySelector.append", "#articles-menu>.articles-type:last-of-type>.article:last-of-type" ], 0, [ "underline-hover" ], 0, [ ["href","#"] ], "underline animation" );
    newElement( "li", [ "querySelector.append", "#articles-menu>.articles-type:last-of-type" ], 0, [ "article" ] );
        newElement( "a", [ "querySelector.append", "#articles-menu>.articles-type:last-of-type>.article:last-of-type" ], 0, [ "underline-hover" ], 0, [ ["href","#"] ], "end longtext ..." );
newElement( "ul", [ "id.append", "articles-menu" ], 0, [ "articles-type" ] );
newElement( "a", [ "querySelector.append", "#articles-menu>.articles-type:last-of-type" ], 0, [ "underline-hover" ], 0, [ ["href", "#"] ], "Todo-list" );
    newElement( "li", [ "querySelector.append", "#articles-menu>.articles-type:last-of-type" ], 0, [ "article" ] );
        newElement( "a", [ "querySelector.append", "#articles-menu>.articles-type:last-of-type>.article:last-of-type" ], 0, [ "underline-hover" ], 0, [ ["href","#"] ], "eat,sleep,repeat" );
    newElement( "li", [ "querySelector.append", "#articles-menu>.articles-type:last-of-type" ], 0, [ "article" ] );
        newElement( "a", [ "querySelector.append", "#articles-menu>.articles-type:last-of-type>.article:last-of-type" ], 0, [ "underline-hover" ], 0, [ ["href","#"] ], "how to ask 101" );
    newElement( "li", [ "querySelector.append", "#articles-menu>.articles-type:last-of-type" ], 0, [ "article" ] );
        newElement( "a", [ "querySelector.append", "#articles-menu>.articles-type:last-of-type>.article:last-of-type" ], 0, [ "underline-hover" ], 0, [ ["href","#"] ], "long text limit testsssss" );